[default]
convention = "snake"

[[for_patterns]]
pattern = "*.toml"
convention = "pascal"

[[for_patterns]]
pattern = "*.md"
convention = "upper_snake"

[[for_patterns]]
pattern = "./LICENSE"
convention = "upper_snake"

[[for_patterns]]
pattern = "./Cargo.*"
convention = "pascal"

[[for_patterns]]
pattern = "./Dockerfile*"
convention = "pascal"

[[for_patterns]]
pattern = "**/__*__/"
convention = "/^(/"
